### ISSUE TITLE
HEX COLOR IN MENTION AND SOUNDS

### ISSUE THREAD

**Issue by HonzasikCZ** [TectHost/TChat#1]
Hello!

I tried to put a hex color in the mentions but it didn't work:
Screen:
![obrazek](https://github.com/user-attachments/assets/ff80bd93-1295-4254-8f94-b2e3a2d6e6e1)

I hope it gets fixed soon and have a nice rest of the day!
It would also be good if you could add a sound to mentions when a player mentions someone.

**Comment by Tect-host** [comment]
Thanks for your report!

It will be fixed in version 4.0.4
