### ISSUE TITLE
[FEATURE REQUEST] Please implement randomness to the chatgames questions order

### ISSUE THREAD

**Issue by christinloehner** [TectHost/TChat#12]
**[FEATURE REQUEST] Please implement randomness to the chatgames questions order**

We all love the questions in chat, but they are posted in numerous order. That means, you always know the order and which question comes next. That makes it a bit boring.

Please implement randomness to the questions. They should be asked in random order. Then it makes sense to create more than 20 questions. Without randomness, this makes no sense. :-)

**Comment by Tect-host** [comment]
I will add it for the next update, I didn't think of that, thanks for the suggestion!
