### ISSUE TITLE
Doesn't work with cyrillic symbols

### ISSUE THREAD

**Issue by RealKomander** [TectHost/TChat#3]
<img width="467" alt="image" src="https://github.com/TectHost/TChat/assets/124439290/0e5506e6-cb7c-440b-8cd2-d943aa926d5a">

Maybe I need to configure PAPI? Anyways, it's confusing

**Comment by TectHost** [comment]
What are you trying to put in the join mesage?

**Comment by RealKomander** [comment]
> What are you trying to put in the join mesage?

&e%player% приспичило посрать &6[+]

**Comment by RealKomander** [comment]
Don't translate this phrase btw 💀
