### ISSUE TITLE
TChat over taking luckperms

### ISSUE THREAD

**Issue by rlawrence32** [TectHost/TChat#6]
Hello, i'm new in the dev world and only know simplistic code. How do i prevent TChat from overtaking luckperm prefixes?

**Comment by rlawrence32** [comment]
I fixed the issue. I use saberfactions, and now the faction prefix isn't showing up in chat, anyway i can fix that?

**Comment by rlawrence32** [comment]
Also using essentialdiscord, now the chat messages aren't coming through to the discord chat

**Comment by rlawrence32** [comment]
thanks for the speedy reply guys appreciate it sm

**Comment by TectHost** [comment]
Sorry for the delay, read Spigot's page, first line
