### ISSUE TITLE
Anti-Cap Feature is broken ?

### ISSUE THREAD

**Issue by XPaladiumyX** [TectHost/TChat#8]
Cap Option Is Broken even disabled it still doen't let players say anything "LIKE THAT"
I made everything on false in config.yml and even with every features false + a server restart the anti cap still enabled or does there anything else doing this outside of config.yml ? I'm asking that here cause there no discord for support.

**Comment by Tect-host** [comment]
I will check it out, our support discord: https://dc.tect.host/

**Comment by XPaladiumyX** [comment]
Oh great :D

**Comment by XPaladiumyX** [comment]
I want to add also that if i use cap letter when i am op it works.

**Comment by Tect-host** [comment]
Yes, this function already exists in TChat, but it does not work for the same reason that does not work to disable anti cap (the Banned Words turns the entire sentence in lowercase to check for banned words and I did not think at the time that would affect this system) is corrected in 4.1.3, now the Banned Words do not differentiate uppercase and lowercase
