### ISSUE TITLE
Add MOTD

### ISSUE THREAD

**Issue by PeppoDevStudio** [TectHost/TChat#9]
Hi, I saw that this plugin is great, could you add a section in which to put MOTD custom?

**Comment by Tect-host** [comment]
Hi, if by MOTD you mean join message, it can be done with the joins.yml, the join message has multi line support, so you could put a blank line to separate the join message and the MOTD.

If by MOTD you mean the text in the multiplayer selector, TChat will not have such an option.

**Comment by PeppoDevStudio** [comment]
Yes, I mean the MOTD with the image, it would be nice if you added this thing too. Unfortunately I used an old plugin that also had this functionality and since I saw that yours is always updated I tried to ask if you could add it.

**Comment by Tect-host** [comment]
Yes, the image I plan to add it soon, I was doing some tests recently, I will add a special section for MOTD with image option soon, thanks for your suggestion

**Comment by PeppoDevStudio** [comment]
Thank you very much!
